name: build-image

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-arch:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: macos-latest
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/playground:${{ matrix.arch }} \
            --file Dockerfile \
            --push \
            .

  merge-manifest:
    needs: build-arch
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - run: |
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/playground:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/playground:amd64 \
            ${{ secrets.DOCKERHUB_USERNAME }}/playground:arm64
