name: build-image

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1" # build every monday

jobs:
  build-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/playground:${{ matrix.arch }} \
            --file Dockerfile \
            --push \
            .

  merge-manifest:
    needs: build-arch
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - run: |
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/playground:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/playground:amd64 \
            ${{ secrets.DOCKERHUB_USERNAME }}/playground:arm64
