name: build-image

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yaml"
  pull_request:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yaml"
  schedule:
    - cron: "0 0 * * 1" # build every monday

jobs:
  build-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/playground:latest
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/playground:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/playground:buildcache
          push: true
